refactor: unification of error and help storybook stories
kiwicom/orbit pull request #2179
Opened 2020-08-26 11:59 UTC by filipdanisko

2020-08-27 12:26 UTC, vepor approved these changes

2020-08-27 12:29 UTC, silvenon requested changes

2020-08-27 12:29 UTC, silvenon commented on packages/orbit-components/src/Select/Select.stories.js
> +  )
`Select` already has stories "With help message" and "With error message".

2020-08-28 11:58 UTC, silvenon approved these changes

2020-08-28 11:59 UTC, merged