feat(Packages): import orbit-design-tokens
kiwicom/orbit pull request #2188
Opened 2020-08-27 09:49 UTC by vepor

2020-08-27 12:05 UTC, silvenon commented
You need to add `orbit-design-tokens`' `build` script in `build-ci`.

2020-08-28 13:19 UTC, filipdanisko commented on packages/orbit-design-tokens/src/index.d.ts
> +export declare const GetTokens: (customFoundation?: CustomFoundation) => Tokens;
Just a quick fix of exported types, did not wanted to do that in the orbit-design-tokens repository
```suggestion
export declare const fromPlainObject: (themePaletteColors: ThemePaletteColors) => Tokens;
export declare const getTokens: (customFoundation?: CustomFoundation) => Tokens;
```

2020-11-04 12:42 UTC, silvenon requested changes

2020-11-04 12:42 UTC, silvenon commented on .github/workflows/test.yml
> +        run: yarn install && yarn bootstrap && yarn orbit-design-tokens build
Better add another step below named `Build design tokens` for now, just to be explicit about it, later we will work on adding more sense to our scripts.

2020-11-04 12:42 UTC, silvenon commented on packages/orbit-design-tokens/.gitignore
> +.vscode
You can remove `.node_modules`, `.vscode` and `.idea`, they are already covered by our root `.gitignore`.

2020-11-04 12:42 UTC, silvenon commented on packages/orbit-design-tokens/.npmrc
> +access=public
Deleting this file should be fine, but just in case add `"private": false` to `package.json`.

2020-11-04 13:22 UTC, silvenon approved these changes

2020-11-04 14:48 UTC, merged