chore: add GitHub action for deploy to surge
kiwicom/orbit pull request #2189
Opened 2020-08-27 10:13 UTC by vepor

2020-08-28 06:55 UTC, silvenon requested changes
Minor stuff, but otherwise 💚

2020-08-28 06:55 UTC, silvenon commented on .github/workflows/deploy.yml
> +            */*/node_modules
```suggestion
          path: **/node_modules
```

2020-08-28 06:55 UTC, silvenon commented on .github/workflows/deploy.yml
> +        run: npm install -g lerna
If this is for `lerna bootstrap`, Lerna is already a dependency of this project.

2020-08-28 12:46 UTC, silvenon submitted a review, later dismissed

2020-08-28 13:05 UTC, vepor commented
Action works properly, but surge doesn't want to actually publish anything. Will fix it later.

2020-08-29 21:08 UTC, silvenon approved these changes

2020-09-01 10:52 UTC, merged