feat(Eslint): add rules for enforcing readOnly types on TS/Flow
kiwicom/orbit pull request #2331
Opened 2020-10-13 10:13 UTC by aalises

Adds rules for enforcing `readonly` and `exact` types on Typescript and Flow

2020-10-20 10:55 UTC, silvenon requested changes
I was slightly nervous about these exact types breaking consumer code, but I tried it in `frontend/frontend` and everything worked fine. 🙂

2020-10-20 10:55 UTC, silvenon commented on config/eslintJS.js
> +    "flowtype/require-readonly-react-props": "error",
It turns out that `flowtype/require-readonly-react-props` unfortunately doesn't detect props types in definition files, so it isn't useful for us, you can remove it.

2020-10-20 10:55 UTC, silvenon commented on config/eslintTS.js
> +    "@typescript-eslint/prefer-readonly": "error",
We don't need this rule as it's not affecting our code. Can you disable `prefer-readonly-parameter-types` for the problematic file using an ESLint disable directive or `overrides` field?

2020-10-20 12:17 UTC, aalises commented on package.json
> +    "eslint-config-prettier": "^6.12.0",
Not quite!! was part of some tests to see what was wrong with the `Maximum Call Exceeded`

2020-10-21 08:34 UTC, vepor submitted a review, later dismissed

2020-10-21 09:44 UTC, silvenon approved these changes
Amazing, thank you so much!!

2020-10-21 09:44 UTC, silvenon commented on .eslintrc.js
> +    {
```suggestion
    // some ESLint rules fail in certain cases, so we're disabling them
    {
```

2020-10-21 09:45 UTC, silvenon approved these changes

2020-10-21 09:51 UTC, merged