feat(Tag): Icon prop removed, changed colors
kiwicom/orbit pull request #2403
Opened 2020-10-26 06:09 UTC by mainframev

BREAKING CHANGE
- Icon prop removed

I hope i got it right about colors, plz check if it's correct tokens @vepor

2020-12-01 11:10 UTC, silvenon requested changes
Otherwise looks good, and stories work fine. 👍

2020-12-08 11:26 UTC, vepor requested changes
One last thing to resolve - the states of colors. Put it into the original thread on Slack.

2020-12-08 11:26 UTC, vepor commented on packages/orbit-components/src/Tag/index.js
> +    ${({ actionable }) =>
Could be moved to the first function in the top - if we want to go with one function 🙂

2020-12-08 11:26 UTC, vepor commented on packages/orbit-components/src/Tag/index.js
>          <CloseContainer
The `CloseContainer` component doesn't have any transition 😕

2020-12-09 18:52 UTC, silvenon requested changes
Other than this minor suggestion everything else looks good. Regarding colors I'm not in the loop (not sure where that Slack thread is), so I'll leave it up to @vepor to confirm.

2020-12-09 18:52 UTC, silvenon commented on packages/orbit-components/src/Tag/__tests__/index.test.js
> +    userEvent.click(screen.getByLabelText("close"));
```suggestion
    userEvent.click(screen.getByRole("button", { name: "close" }));
```

2020-12-10 09:18 UTC, silvenon approved these changes

2021-01-22 13:52 UTC, silvenon approved these changes
Looks good, and the close button has transitions now 👍

2021-01-22 17:38 UTC, merged