Fix/list choices
kiwicom/orbit pull request #2474
Opened 2020-11-06 15:25 UTC by mainframev

[plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1604581597225600)
[jira issue](https://jira.kiwi.com/browse/ORBIT-1472)

2020-11-09 11:06 UTC, silvenon requested changes
Test please 🙏 `userEvent.tab` takes `tabIndex` into account so it should be possible.

2020-11-09 11:06 UTC, silvenon commented on packages/orbit-components/src/ListChoice/index.js
> +  tabIndex = 0,
Considering that this seems to be a separate feature, add it to a separate commit so that it's visible in the changelog.

2020-11-10 10:57 UTC, mainframev commented
> Test please 🙏 `userEvent.tab` takes `tabIndex` into account so it should be possible.

i'll resolve this by separate PR

2020-11-10 11:01 UTC, vepor approved these changes

2020-11-10 13:14 UTC, silvenon approved these changes

2020-11-10 13:14 UTC, merged