feat: SmartPassIllustration component
kiwicom/orbit pull request #2504
Opened 2020-11-13 16:59 UTC by mainframev

2020-11-14 08:35 UTC, mainframev commented
- We shoud pick some names for images, now i just named them as `v1, v2, v3 ...` :)

2020-11-18 11:36 UTC, silvenon requested changes
Also delete `.DS_Store` and add it to `.gitignore`.

2020-11-18 11:36 UTC, silvenon commented on packages/orbit-components/src/SmartPassIllustration/index.js
> +  );
Instead I recommend something like this:

```jsx
import * as Illustrations from "./components"

// ...

const Illustration = Illustrations[`SmartPass${name.toUpperCase()}`]
if (Illustration) {
  return (
    <Illustration name={name} primary={primary} height={height} secondary={secondary} {...props} />
  );
}
return null;
```

2020-11-18 11:36 UTC, silvenon commented on packages/orbit-components/src/index.js.flow
> +declare export var SmartPassIllustration: SmartPassIllustrationType;
Should be added to `.d.ts` file as well, no?

2020-11-18 11:36 UTC, silvenon commented on packages/orbit-components/src/SmartPassIllustration/__tests__/index.test.js
> +    expect(screen.getByRole("img")).toHaveAttribute("aria-labelledby", "aria-labeled");
Maybe also check `<title>`? I wonder if `ByTitle` will work for this case.

2020-11-18 11:41 UTC, mainframev commented on packages/orbit-components/src/SmartPassIllustration/components/SmartPassV1.js
> +      alt={alt || name}
yes, forgot to remove it

2020-11-19 13:05 UTC, silvenon requested changes

2020-11-19 13:05 UTC, silvenon commented on packages/orbit-components/src/SmartPassIllustration/components/SmartPassV2.js
> +      aria-labelledby={ariaLabelledby}
I don't know what passing `ariaLabelledby` to `SmartPassIllustration` and forwarding it to SVG elements does, but I assume you researched it and know that it's the right thing to do. 🤷‍♂️

2020-11-19 13:06 UTC, mainframev commented on packages/orbit-components/.gitignore
> +src/SmartPassIllustration/.DS
i dont know, i did not put it there :D

2020-11-19 14:24 UTC, silvenon approved these changes

2020-11-19 14:25 UTC, merged