test(Pagination): rewrite to testing library
kiwicom/orbit pull request #2539
Opened 2020-11-26 16:55 UTC by mainframev

2020-11-27 12:21 UTC, silvenon requested changes

2020-11-27 12:21 UTC, silvenon commented on packages/orbit-components/src/Pagination/__tests__/index.test.js
> +    expect(buttons.slice(-1)[0]).toHaveAttribute("disabled");
```suggestion
    expect(buttons.slice(-1)[0]).toBeDisabled();
```

2020-11-27 12:21 UTC, silvenon commented on packages/orbit-components/src/Pagination/__tests__/index.test.js
> +    expect(screen.getAllByRole("button")[0]).toHaveAttribute("disabled");
```suggestion
    expect(screen.getAllByRole("button")[0]).toBeDisabled();
```

2020-11-27 12:59 UTC, mainframev commented on packages/orbit-components/src/Pagination/__tests__/index.test.js
> +    userEvent.click(buttons.slice(-1)[0]);
ButtonLink supports `aria-label`, it has prop `title` which is passed to `ButtonPrimitive` and there is `aria-label={title}`

2020-11-27 13:11 UTC, mainframev commented on packages/orbit-components/src/Pagination/__tests__/index.test.js
> +    userEvent.click(buttons.slice(-1)[0]);
+ i tried it with `{name: "Next"}` and it was not working, so i've added aria-labels via `title` prop, now test passes with `screen.getByLabelText`

2020-11-28 21:45 UTC, silvenon commented on packages/orbit-components/src/Pagination/__tests__/index.test.js
> +    userEvent.click(buttons.slice(-1)[0]);
This suggestion has grown outside the scope of this PR and has been moved to #2542.

2020-11-28 22:09 UTC, silvenon commented
I assume you plan to rebase and update tests now that you can mock `useMediaQuery`?

2020-11-28 22:12 UTC, mainframev commented
> I assume you plan to rebase and update tests now that you can mock `useMediaQuery`?

yes, sorry for not mentioning it

2020-11-30 13:53 UTC, silvenon approved these changes
Looks good!

In the next PR please also add tests for mobile, considering that you refactored the component with `useMediaQuery`. You can use Modal tests as a reference how to mock different breakpoints for different tests, just don't forget to restore at the end of each test so that the tests don't affect each other.

Also add a test to check whether passing `hideLabels` (short for `hideLabels={true}`) indeed hides the labels, and that `hideLabels={false}` shows them. You can check for that with `toHaveTextContent`.

2020-11-30 13:53 UTC, merged