feat(eslint-orbit): add unique-ids rule
kiwicom/orbit pull request #2671
Opened 2021-01-18 10:35 UTC by mainframev

I added new rule `unique-id`, for some [svg references ](https://developer.mozilla.org/en-US/docs/Web/SVG/Element). Did not include all, but most used. If you think we should add them more - can be discussed here. Also did not write test to check them all, not sure if it's needed.

2021-01-18 16:57 UTC, silvenon reviewed
I recommend two more changes:

1. try to extract this rule into a new internal package (`"private": true` in `package.json`) called something like `@kiwicom/eslint-plugin-orbit-internal`, however I don't know if this will work as easily as I hope 🤞
2. make the rule less sophisticated, it doesn't even need to be SVG-oriented because we want it to work for other elements as well, I recommend starting by checking `id` attributes of _any_ element or component, and you don't need to count them, the problematic part should be if the value of `id` is a `Literal`

To elaborate the 2nd suggestion: AFAICT, this rule wouldn't have caught the problems you ran into because the duplicate `id`s weren't in the same file, they were in the same HTML document because the same component was being rendered more than once, correct? This is why I suggest that the rule simply complains if the `id` value is a `Literal`, because statically speaking you cannot possibly know whether the component in that file is being rendered more than once, so you don't even have to try.

2021-01-18 16:57 UTC, silvenon commented on packages/eslint-plugin-orbit-components/src/rules/svgUniqueId.ts
> +  create: (context: Rule.RuleContext) => {
I also recommend adding the `meta` object describing the rule's `type` (IMO `"problem"`) and `docs`.

2021-01-18 16:57 UTC, silvenon commented on packages/eslint-plugin-orbit-components/src/rules/svgUniqueId.ts
> +                  message: `${attr.name.name}="${value}", should have unique id`,
I think that the error message should recommend using the `useRandomID` hook that you can create as part of this PR, as described in the Jira ticket.

2021-01-30 14:19 UTC, mainframev commented
@silvenon resolved everything, seems to work fine

2021-02-03 14:10 UTC, silvenon requested changes
Awesome work! 💯

2021-02-03 14:10 UTC, silvenon commented on packages/eslint-plugin-orbit-internal/src/configs/recommended.ts
> +  },
It doesn't seem like it should be the concern of this plugin's recommended config to set this. It might overwrite settings of a plugin before it.

2021-02-03 14:10 UTC, silvenon commented on packages/eslint-plugin-orbit-internal/src/rules/unique-id.ts
> +        JSXAttributes.forEach(n => {
Just curious, would it be different if you put the logic that's inside this loop in the place of the `JSXAttributes.push(node)` above?

2021-02-03 14:10 UTC, silvenon commented on packages/eslint-plugin-orbit-internal/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
We should have a single `yarn.lock` file.

2021-02-03 14:10 UTC, silvenon commented on packages/orbit-components/src/SmartPassIllustrations/illustrations/SmartPassV1.js
> +          id={randomIDLinear}
Wonderful, it already caught some problems! 🏆

2021-02-04 11:14 UTC, silvenon approved these changes

2021-02-04 13:19 UTC, merged