improve: cleanup Babel setup
kiwicom/orbit pull request #2752
Opened 2021-02-19 11:55 UTC by silvenon

The root Babel configuration was mostly applying to `@kiwicom/orbit-components`, so now it has been moved there, so that it's responsible for a single package. Also, considering that Storybook stories are importing the source code it made a lot of sense to reuse the same Babel configuration in Storybook's webpack configuration, instead of maintaining a separate Babel configuration there.

`@adeira`'s Babel preset uses Flow, and considering that we plan to gradually switch to TypeScript, I broke it down into plugins that we actually (might) need, and it turned out that the list is pretty simple.  Now we know exactly what our Babel configuration does and it's much more flexible.

2021-02-22 09:52 UTC, silvenon commented on .github/contribution/testing-conventions.md
> -- Samsung Internet 11.1-11.2
I didn't realize this part changed, I'll have to figure out why, but ignore it for now.

2021-02-23 12:29 UTC, vepor requested changes
As we discussed already, so just you won't forget.

2021-02-23 12:29 UTC, vepor commented on docs/babel.config.js
> +  presets: ["gatsby", "@babel/preset-typescript"],
We don't have `@babel/preset-typescript` anywhere as dependency.

2021-02-23 15:36 UTC, silvenon commented on .github/contribution/testing-conventions.md
> -- Samsung Internet 11.1-11.2
For posterity: this turned out to be a result of `browserslist` update in db33af97ed4b890fbdf22c378e3224e0f15d901d, but our setup for automatically updating the this Markdown file isn't sophisticated enough to catch that.

2021-02-23 15:57 UTC, vepor approved these changes

2021-02-23 16:21 UTC, merged