chore(eslint-plugins): merge internal and eslint-plugin-orbit
kiwicom/orbit pull request #2819
Opened 2021-03-09 16:45 UTC by mainframev

2021-03-10 14:41 UTC, vepor requested changes

2021-03-10 14:41 UTC, vepor commented on packages/eslint-plugin-orbit-components/package.json
> +    "eslint-plugin-orbit-components": "^0.3.2"
Why is this here? 🤔

2021-03-10 14:41 UTC, vepor commented on .eslintrc.js
> +      files: ["packages/eslint-plugin-orbit/src/**"],
`packages/eslint-plugin-orbit-components/src/**` ?

2021-03-11 08:46 UTC, mainframev commented on packages/eslint-plugin-orbit-components/package.json
> +    "eslint-plugin-orbit-components": "^0.3.2"
🤷🏻 weird, thanks

2021-03-11 11:19 UTC, silvenon submitted a review, later dismissed

2021-03-11 11:20 UTC, vepor approved these changes

2021-03-15 00:04 UTC, merged