feat(docs): rework roadmap based on design
kiwicom/orbit pull request #2870
Opened 2021-04-06 07:25 UTC by CollierCZ

In the masonry layout, items get added to columns based on their order, rather than height, so the result isn't always perfect. But checking based on height is slow, so it seemed acceptable. Let me know if you'd prefer the other way.

2021-04-06 12:22 UTC, silvenon requested changes
I'm wondering what to do about the TOC wrapper when there's no TOC 🤔  I think it's alright to still reserve that space to keep design consistency, but there shouldn't be an empty "Table of contents" title on mobile.

2021-04-06 12:22 UTC, silvenon commented on docs/src/pages/roadmap.tsx
> +      what&apos;s already designed and the state it&apos;s in, visit{" "}
Use smart apostrophes, like above:
```suggestion
      what’s already designed and the state it’s in, visit{" "}
```
There's one more below.

2021-04-06 17:51 UTC, silvenon commented on docs/src/components/MasonryLayout.tsx
> +  return <div style={{ display: "flex" }}>{result}</div>;
Just to add a better reason: using inline styles won't include vendor prefixes for declarations that need them, like Flexbox.

2021-04-07 08:37 UTC, CollierCZ commented on docs/src/components/MasonryLayout.tsx
> +  return <div style={{ display: "flex" }}>{result}</div>;
Yes, I'd planned to get rid of this, just overlooked it once I got the feature working. I'll keep your love of Tailwind just between us.

2021-04-07 08:37 UTC, CollierCZ commented on docs/src/components/MasonryLayout.tsx
> +const MasonryLayout = ({ columns = 2, gap = 24, children }: Props) => {
Yes! Meant to do it, but slipped my mind.

2021-04-07 08:56 UTC, CollierCZ commented
> I'm wondering what to do about the TOC wrapper when there's no TOC 🤔 I think it's alright to still reserve that space to keep design consistency, but there shouldn't be an empty "Table of contents" title on mobile.

Not sure about the space on the right, but I can definitely remove the collapse on mobile.

2021-04-07 09:10 UTC, CollierCZ commented
I realized I already had a check to hide the ToC when it wasn't populated, but then its structured change. So I fixed the check. And it seemed to hide the space on the right too, so that's how it is for now.

2021-04-07 10:07 UTC, silvenon submitted a review, later dismissed
After this you can merge right away.

2021-04-07 12:25 UTC, merged