Feat/verce banner
kiwicom/orbit pull request #2873
Opened 2021-04-06 18:06 UTC by mainframev

I've refactored a bit footer component, I will have to put a `Vercel` logo there soon. Noticed, that it can be done a bit more simply via `Stack`. Now it much the initial design, since the height of both parts of footer are equal to the height of the proposed design from Will.

2021-04-06 18:07 UTC, mainframev commented
@silvenon could you check 🙏🏻 ? if you are agree with the changes

2021-04-07 10:49 UTC, silvenon requested changes

2021-04-07 10:49 UTC, silvenon commented on docs/src/components/Footer.tsx
> +              <Stack inline grow={false} spacing="none">
You need to add spacing between label and the switch. This is how the footer looked at 367 px before:

![Screen Shot 2021-04-07 at 12 16 15](https://user-images.githubusercontent.com/471278/113854206-e8207400-979e-11eb-87cd-eb4a3dd0fcb5.png)

and after your change:

![Screen Shot 2021-04-07 at 12 15 47](https://user-images.githubusercontent.com/471278/113854183-df2fa280-979e-11eb-8f3f-173541c8d416.png)

Plus, the switch is overflowing the footer on the right (the screenshot is taken full-width).

You can also notice that the "Built & maintained by Kiwi.com" part is no longer centered, not sure if that was on purpose.

2021-04-09 10:42 UTC, silvenon approved these changes
Looks good now 👍

2021-04-09 10:42 UTC, merged