chore: remove docs deploy on surge
kiwicom/orbit pull request #2904
Opened 2021-04-22 18:06 UTC by mainframev

2021-04-23 07:46 UTC, silvenon submitted a review, later dismissed

2021-04-25 14:04 UTC, mainframev commented
@silvenon any idea why it fails? seems like it can't apply artifact 🤔

2021-04-28 09:11 UTC, CollierCZ requested changes

2021-04-28 09:11 UTC, CollierCZ commented on .github/workflows/test_and_deploy.yml
> +        run: npx lerna run --ignore orbit.kiwi build
This does not leave out the docs build. I think using `@kiwicom/orbit.kiwi` would work, but haven't checked it.

2021-04-28 09:11 UTC, CollierCZ commented on .github/workflows/test_and_deploy.yml
>        - name: Check docs links
This step requires a build of the docs. Removing the build means that the check isn't done.

2021-04-28 09:30 UTC, CollierCZ commented
> @silvenon any idea why it fails? seems like it can't apply artifact 🤔

I think it's because the artifact is being saved as a top-level folder, so that's how it's extracted. Before, when it was saving two folders, it saved them in separate folders that were unpacked correctly. Now it's unpacking to the root instead of `packages/orbit-components/.out`.

You have to use the path option for the step: https://github.com/actions/download-artifact#download-a-single-artifact

2021-04-28 12:24 UTC, mainframev commented
> > @silvenon any idea why it fails? seems like it can't apply artifact 🤔
> 
> I think it's because the artifact is being saved as a top-level folder, so that's how it's extracted. Before, when it was saving two folders, it saved them in separate folders that were unpacked correctly. Now it's unpacking to the root instead of `packages/orbit-components/.out`.
> 
> You have to use the path option for the step: https://github.com/actions/download-artifact#download-a-single-artifact

Ah, yes, look like it works. Did not notice that little thing, thanks a lot :)

2021-04-28 15:02 UTC, silvenon approved these changes

2021-04-28 15:04 UTC, merged