fix(Popover): split renders
kiwicom/orbit pull request #2905
Opened 2021-04-23 16:43 UTC by mainframev

2021-05-03 14:25 UTC, silvenon requested changes
I checked this locally and it works 👍  The code seems straightforward, I would only suggest trying to add a unit test, as the Jira ticket description says as well, you can add a separate test file so that you can mock `useMediaQuery` differently. I was thinking of adding a story alternatively in case there's no way to test it with unit tests, but it would be better to use Cypress tests in that case, which we don't have yet.

2021-05-03 14:25 UTC, silvenon commented on packages/orbit-components/src/Popover/components/ContentWrapperMobile.js
> -  max-height: ${({ windowHeight, actionsHeight }) => `${windowHeight - actionsHeight - 32}px`};
I can't find where this `windowHeight` was coming from before you started computing it inside 😄  Was it being passed from outside somehow…?

2021-05-04 14:45 UTC, mainframev commented on packages/orbit-components/src/Popover/components/ContentWrapperDesktop.js
> +  const windowHeight = typeof window !== "undefined" ? window.innerHeight : 0;
that's not the part of the pull request, i just moved the content, it was there, the aim of this PR is to fix the issue in the descriptionon

2021-05-04 14:45 UTC, closed without merging

2021-05-04 14:48 UTC, mainframev commented
Closed. Replaced by #2923