feat: horizontallScroll utility component
kiwicom/orbit pull request #2917
Opened 2021-04-29 14:57 UTC by mainframev

2021-05-03 16:00 UTC, silvenon requested changes
Other than comments below, it seems to work good 👍

2021-05-03 16:00 UTC, silvenon commented on packages/orbit-components/src/HorizontalScroll/__tests__/index.test.js
> +`;
Why style a div in unit tests?

2021-05-03 16:00 UTC, silvenon commented on packages/orbit-components/src/HorizontalScroll/index.js
> +const StyledChild = styled.div``;
You don't need this.

2021-05-03 16:00 UTC, silvenon commented on packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.js
> +        <CustomDiv key={key}>{key}</CustomDiv>
I'd try using a combination of `Box` + `Text` instead, or at least use the sans-serif font.

2021-05-04 11:52 UTC, mainframev commented on packages/orbit-components/src/HorizontalScroll/README.md
> +| spacing   | [`Spacing`](###Spacing) |                    | "small" | the spacing between children elements |
what's wrong with `###`? it looks even better, i think :)

2021-05-04 11:53 UTC, mainframev commented on packages/orbit-components/src/HorizontalScroll/index.d.ts
> +  readonly children: React.ReactNode;
hm, this component always should have children, so i think it's should be required 🤔

2021-05-04 11:56 UTC, mainframev commented on packages/orbit-components/src/HorizontalScroll/index.js
> +  const { current: childRef } = React.useRef<(number | null)[]>([]);
not a mistake, personal preference to have it like that.

2021-05-04 11:57 UTC, mainframev commented on packages/orbit-components/src/HorizontalScroll/index.js
> +                <StyledChild ref={r => (childRef[idx] = r && r.clientHeight)}>{child}</StyledChild>
what pattern do you suggest then?

2021-05-04 15:59 UTC, silvenon commented on packages/orbit-components/src/HorizontalScroll/index.js
> +                <StyledChild ref={r => (childRef[idx] = r && r.clientHeight)}>{child}</StyledChild>
I think this should work:
```jsx
<StyledChild ref={r => {
  if (r) childRef[idx] = r.clientHeight
}}>
  {child}
</StyledChild>
```

2021-05-04 16:05 UTC, silvenon commented on packages/orbit-components/src/HorizontalScroll/README.md
> +| spacing   | [`Spacing`](###Spacing) |                    | "small" | the spacing between children elements |
As a link it doesn't work, try it. It sounds like you thought I was suggesting changing the heading level.

2021-05-05 12:53 UTC, mainframev commented on packages/orbit-components/src/HorizontalScroll/README.md
> +| spacing   | [`Spacing`](###Spacing) |                    | "small" | the spacing between children elements |
for me worked :thinking:

2021-05-05 14:29 UTC, merged