docs: implement side navigation
kiwicom/orbit pull request #2918
Opened 2021-04-29 22:39 UTC by silvenon

I hated coding this, every now and then I had to take walks to cool off. I'm looking forward to discussing better styling practices.

I postponed bookmarks redesign to another PR, so that part is unfinished, but side navigation both desktop and mobile should work.

2021-04-29 22:48 UTC, silvenon reviewed
A couple of notes to help with review.

2021-04-29 22:48 UTC, silvenon commented on docs/src/images/orbit-logo.svg
> +</svg>
Logos are now updated, they are circular and the glyph is SVG rather than PNG.

2021-04-29 22:48 UTC, silvenon commented on docs/src/mdx-components.tsx
> +    whiteSpace="normal"
The tables where horizontally overflowing in `DocLayout.tsx` because table cells by default don't wrap, not sure why.

2021-04-29 22:48 UTC, silvenon commented on docs/src/documentation/01-getting-started/01-for-designers/01-kiwi.mdx
> -  - /getting-started/for-designers/
This page appears to be redirect to itself, which was causing problems.

2021-04-29 22:48 UTC, silvenon commented on docs/src/components/Tabs.tsx
> +};
These changes attempt to make the tab shadow trick more stable, the prior implementation was interfering with examples.

2021-04-29 23:28 UTC, silvenon commented
It's failing for the same reason as #2911 was previously failing, but that will be fixed once that's merged and I rebase, so it's fine to review.

2021-04-30 11:33 UTC, mainframev requested changes

2021-04-30 11:33 UTC, mainframev commented on docs/src/components/DocLayout/index.tsx
> +                  <StyledMobileOutdent>
here is a visual bug, when the icon is not placed on the bottom
![Screenshot 2021-04-30 at 13 20 47](https://user-images.githubusercontent.com/14054752/116688388-ea997680-a9b6-11eb-99d6-7a729ab0ee37.png)

2021-04-30 11:57 UTC, mainframev commented
**_here are few visual things I noticed, that can be quickly fixed:_**
1. Bookmarks modal and Search modal now appear in the middle, it should be placed as before, about 30% from the top. 
2. Bookmarks modal does not have the same border-radius as the Search modal.
3. When I'm clicking on the sidenav item, the whole content is jumping, because of the main content width, it depends on the amount of content inside, so it should have some min-width, I suppose, to prevent that kind of jumping content.
4. Sidenav item should have a smaller arrow and the gap between text and arrow should be smaller. In Figma, it looks a bit different 🤔 
![Screenshot 2021-04-30 at 13 43 11](https://user-images.githubusercontent.com/14054752/116690678-081c0f80-a9ba-11eb-900f-14602aa77ec5.png)

2021-04-30 11:58 UTC, mainframev reviewed
here are few visual things I noticed, that can be quickly fixed:

Bookmarks modal and Search modal now appear in the middle, it should be placed as before, about 30% from the top.
Bookmarks modal does not have the same border-radius as the Search modal.
When I'm clicking on the sidenav item, the whole content is jumping, because of the main content width, it depends on the amount of content inside, so it should have some min-width, I suppose, to prevent that kind of jumping content.
Sidenav item should have a smaller arrow and the gap between text and arrow should be smaller. In Figma, it looks a bit different 🤔
![Screenshot 2021-04-30 at 13 43 11](https://user-images.githubusercontent.com/14054752/116692052-0eab8680-a9bc-11eb-8eb4-1c6808c49f11.png)

2021-04-30 11:58 UTC, mainframev commented on docs/src/components/DocNavigation/index.tsx
> +  item: NavigationItem;
can you create an interface and pass it here? should look better :) 
you can create a separate file inside the folder `DocNavigation` called `records` or `interfaces` and pass all types there, so this file will look more cleaner, just a tip.

2021-04-30 11:58 UTC, mainframev commented on docs/src/components/DocNavigation/index.tsx
> +      ),
this looks a bit complicated for a default state 🤔  
it should be assigned to some variable at least

2021-04-30 11:58 UTC, mainframev commented on docs/src/components/DocNavigation/primitives/Collapse.tsx
> +export default function Collapse({ expanded, label, hasCategories, children, onClick }: Props) {
it's inside folder `primitives`, in the primitives folder, we usually place only SC primitives, without react components, it's not bad, but it's kinda against our habit, when i open the component inside primitives folder i expect to see only SC components there

so the correct way will be to have separate `Collapse` component and import there these primitives.

2021-04-30 11:59 UTC, mainframev commented on docs/src/components/DocNavigation/index.tsx
> +function DocNavigationItem({
could you also split the `DocNavigationItem` and `DocNavigation` into two different files?

2021-05-04 13:30 UTC, mainframev approved these changes

2021-05-05 14:44 UTC, CollierCZ commented
Hmm. Now the changes propagated immediately, so it was probably just that I needed to clear the cache before trying out this PR. So you can ignore that part. I still get the list twice.

2021-05-07 11:08 UTC, silvenon reviewed
Done with changes, hopefully fixed all the issues.

2021-05-07 11:28 UTC, CollierCZ commented on docs/src/documentation/03-components/02-structure/card/meta.yml
> +description: Separates content into sections. Hi
That was from testing the caching issue and seeing if it applied to description as well. Guess I forgot to get rid of it. 🙈

2021-05-07 14:07 UTC, CollierCZ submitted a review, later dismissed
Other than the failing test, looks good to me!

2021-05-07 18:53 UTC, merged