Improve pipeline speed
kiwicom/orbit pull request #2955
Opened 2021-05-20 19:31 UTC by silvenon

- ci: use better GitHub workflow name
- ci: improve pipeline speed
- improve: make clean script more complete
- improve: add clean scripts for easier testing

2021-05-21 08:11 UTC, CollierCZ requested changes
I like the idea of splitting Storybook with its deploy into a separate workflow (I'm assuming it doesn't require a build of the components). 

Not building the docs pages means that the job to check links in the docs won't work (it depends on built files being present). So I like the idea of avoiding it, but I'm not sure it'll work ideally at the moment.

As far as I know, Cloudflare Pages doesn't use caching or anything for Gatsby, so the builds there will always take longer and I'm not sure it'll save time overall. And not having logs from the builds isn't great, but I hope that'll be solved soon.

2021-05-21 09:24 UTC, mainframev commented on .github/workflows/storybook.yml
> +          node-version: "15"
upgrade also `.node-version` file

2021-05-21 11:19 UTC, silvenon commented
Ok, now I build and test documentation in a separate job in `test.yml`. I updated the PR description to reflect the current state. Now the savings are not spectacular, but are still significant.

2021-05-21 11:21 UTC, mainframev submitted a review, later dismissed

2021-05-21 11:37 UTC, CollierCZ requested changes
The 12 minutes is without any caching for the docs site (because it's a new job and so no cache key existed), so my guess is it'll be less on future builds.

The build logs say they don't include a GitHub access key. That means not all links will be checked because some should come from that component.

The Cloudflare Pages job is still taking close to 20 minutes, which is going to be the bottleneck going forward.

2021-05-21 11:41 UTC, CollierCZ commented
Also, until we upgrade to Gatsby 3 (with webpack 5), I realized we're not taking advantage of the caching we have. i think we should be using incremental builds with the `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES` environment variable set to `true`.

2021-05-21 13:19 UTC, CollierCZ commented on .github/workflows/test.yml
> -          GH_TOKEN: ${{ secrets.GH_TOKEN }}
I think both of the jobs need the token. If the build doesn't have the token, it won't build the contributors and the links to their profile pages won't get checked later.

2021-05-21 14:12 UTC, silvenon commented
I made sure that scripts fail in CI if expected environment variables are missing, and checking links should fail if `docs/public` is missing. (I forgot to also make it fail if `GH_TOKEN` is missing, I'll do that now.)

2021-05-24 11:28 UTC, CollierCZ submitted a review, later dismissed
The incremental builds don't seem to be working. It might be because they want us to use Gatsby Cloud for building/deploys. Or it might be that the hashes of the files are based on absolute paths and those might change between jobs. 🤷‍♂️ Either way, it still is faster, but it's clearing the cache between even content changes.

The GitHub contributors isn't working: https://cca79f77.orbit.pages.dev/getting-started/support/team/#react-components But maybe that's an issue with that component and so outside the scope of this one.

The changes look good in general.

2021-05-24 12:03 UTC, silvenon commented
> The incremental builds don't seem to be working.

Too bad 😕  hopefully we'll be able to switch to Gatsby v3 soon.

> The GitHub contributors isn't working

Yup, it doesn't work on master either, so we need to fix that in a separate PR.

2021-05-24 12:12 UTC, silvenon commented
Nothing new here, just squashing some commits together to tidy up the history. Will merge after passing CI.

2021-05-24 12:21 UTC, merged