feat(ChoiceGroup): increase rendering flexibility
kiwicom/orbit pull request #2983
Opened 2021-06-11 11:49 UTC by silvenon

By accepting a function as `children` we're increasing the flexibility of rendering, for example now people can combine `react-window` with ChoiceGroup.

- [Slack request](https://skypicker.slack.com/archives/C9B1H0ACW/p1622462413007500)

2021-06-11 11:58 UTC, silvenon commented
The spacing between items in the "Render prop" story is off, but it's fine to review otherwise.

2021-06-11 12:19 UTC, silvenon commented
Fixes spacing with some styling gymnastics. 😄 ✅

2021-06-18 11:12 UTC, mainframev commented
this PR creates empty file in ` docs/plugins/table-of-contents/gatsby-node.js ` Seems like not related to this PR.

2021-06-18 11:29 UTC, mainframev requested changes

2021-06-18 11:29 UTC, mainframev commented on packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.js
> +    <ChoiceGroup label="What was the reason for your cancellation?" onChange={() => {}}>
```suggestion
    <ChoiceGroup label="What was the reason for your cancellation?" onChange={action("onChange")}>
```

2021-06-21 12:38 UTC, vepor approved these changes

2021-06-21 12:40 UTC, merged