fix(sandbox): viewport preview
kiwicom/orbit pull request #3018
Opened 2021-07-09 14:47 UTC by mainframev

fixed the viewport previewer, so it applies the width on `Wrapper` before `iframe`, so `iframe` takes that width and `window` inside `iframe` receives proper width

2021-07-12 11:57 UTC, CollierCZ commented
It seems like it's fixed nicely in some places, but other problems exist elsewhere. In [some examples](https://006a0321.orbit.pages.dev/examples/text-types) only the mobile widths (large and small) are available. They also don't have the [right automatic height](https://006a0321.orbit.pages.dev/foundation/typography/#text-styles).

Also, the full-page sandbox seems to have only mobile large, mobile small, desktop and full width. Is that intentional to not have the others?

2021-07-13 07:41 UTC, mainframev commented
> It seems like it's fixed nicely in some places, but other problems exist elsewhere. In [some examples](https://006a0321.orbit.pages.dev/examples/text-types) only the mobile widths (large and small) are available. They also don't have the [right automatic height](https://006a0321.orbit.pages.dev/foundation/typography/#text-styles).
> 
> Also, the full-page sandbox seems to have only mobile large, mobile small, desktop and full width. Is that intentional to not have the others?

fixed

2021-07-14 09:57 UTC, silvenon requested changes

2021-07-14 09:57 UTC, silvenon commented on docs/src/components/ReactExample/helpers.tsx
> +import * as Icons from "@kiwicom/orbit-components/lib/icons";
```suggestion
import * as Icons from "@kiwicom/orbit-components/icons";
```

2021-07-14 09:57 UTC, silvenon commented on docs/src/templates/sandbox/index.tsx
> +  grid-template-columns: 100%;
```suggestion
  grid-template-columns: 1fr;
```

2021-07-14 09:57 UTC, silvenon commented on docs/src/templates/sandbox/index.tsx
> +  const getCurrentWidth = React.useCallback(size => setPreviewWidth(size), []);
`getCurrentWidth` doesn't get a width, it sets it, I recommend a name like `handleChangeRulerSize`.

2021-07-14 12:02 UTC, silvenon approved these changes

2021-07-14 13:46 UTC, merged