docs: visual fixes
kiwicom/orbit pull request #3098
Opened 2021-09-06 20:58 UTC by mainframev

Visual fixes acc. to the [task](https://jira.kiwi.com/browse/ORBIT-1836)

2021-09-07 18:15 UTC, silvenon requested changes

2021-09-07 18:15 UTC, silvenon commented on docs/src/components/ReactExample/Example.tsx
> +  const [bg, setBackground] = React.useState<BgType>("white");
Use a more descriptive name for `bg` to differentiate it from `background`, like `selectedBackground`.

2021-09-07 18:15 UTC, silvenon commented on docs/src/components/ReactExample/components/Board.tsx
> +          </Popover>
Very cool! 😍

2021-09-08 10:42 UTC, mainframev commented on docs/src/components/DocLayout/index.tsx
> +          <Footer />
i don't know, designers decided to remove the gradient on footer

2021-09-09 11:43 UTC, silvenon commented on docs/src/components/DocLayout/index.tsx
> +          <Footer />
We got our answer on Slack: the left navigation should fade out, but not the main content box.

2021-09-09 12:55 UTC, mainframev commented on docs/src/components/DocLayout/index.tsx
> +          <Footer />
Yep, saw that ;)

2021-09-09 15:28 UTC, mainframev commented on docs/src/components/DocLayout/primitives/StyledMobileOutdent.tsx
> +    margin-bottom: 4rem;
yep, shadow will be removed, but margin still has to be there

2021-09-09 17:19 UTC, silvenon commented on docs/src/components/DocLayout/primitives/StyledMobileOutdent.tsx
> +    margin-bottom: 3rem;
Just a reminder, I think this gap is unnecessary. My suggestion is to remove the margin.

<img width="605" alt="Screen Shot 2021-09-09 at 19 17 29" src="https://user-images.githubusercontent.com/471278/132732409-761876c2-7afd-4648-92a0-2235b88dd9af.png">

2021-09-10 18:44 UTC, silvenon approved these changes
Sold!

2021-09-10 18:52 UTC, merged