docs(Gudelines): fix not visible images
kiwicom/orbit pull request #3195
Opened 2021-11-16 17:59 UTC by mainframev

A quick fix for [slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1636970158141300).

2021-11-18 00:25 UTC, silvenon requested changes
By doing this we would be fighting against the tool that's supposed to help us. The reason why this happens is because multiple the containers are set to be as wide as their content, which is `0` in this case because of `position: absolute`, so the content has nowhere to go. Those containers should stretch as wide as they can, so set `align` of relevant Stack components to `stretch`, and do whatever else is necessary.

Let me know if you need help 😉

2021-11-18 02:24 UTC, mainframev commented
> By doing this we would be fighting against the tool that's supposed to help us. The reason why this happens is because multiple the containers are set to be as wide as their content, which is `0` in this case because of `position: absolute`, so the content has nowhere to go. Those containers should stretch as wide as they can, so set `align` of relevant Stack components to `stretch`, and do whatever else is necessary.
> 
> Let me know if you need help 😉

weird, i tried `stretch` and it did not work, maybe i missed something 🤔 I agree that the fix is dirty

2021-11-19 13:44 UTC, silvenon requested changes
Great, works! Just one thing.

2021-11-19 13:44 UTC, silvenon commented on docs/src/data/CHANGELOG.md
> +-   **useToggle:** make typings reflect initial param is optional ([95821c5](https://github.com/kiwicom/orbit/commit/95821c514e8ccf970ec606de219eff301309f914))
Again these changes, we shouldn't commit this. In fact, I don't see a reason for this generated file to be in the version control at all. Could you remove it and add it to `.gitignore`?

2021-11-20 10:07 UTC, silvenon approved these changes

2021-11-20 19:43 UTC, merged