Feat - Rename ThemeProvider to OrbitProvider
kiwicom/orbit pull request #3601
Opened 2022-10-14 08:45 UTC by DSil

[ORBIT-1940](https://jira.kiwi.com/browse/ORBIT-1940)

BREAKING CHANGE: ThemeProvider is now called OrbitProvider.

All references to ThemeProvider were replaced and a new documentation page was also created for the provider.

2022-10-14 16:36 UTC, mainframev requested changes
LGTM

2022-10-14 16:36 UTC, mainframev commented on docs/src/documentation/03-components/14-utility/orbitprovider/01-guidelines.mdx
> +- To have Orbit [theming](/foundation/color/theming/) and [dictionary](/development/guides/dictionary/) on your app.
I think this tab is not needed. Let's left only `react` tab ;)

2022-10-17 09:48 UTC, mainframev approved these changes

2022-10-17 09:49 UTC, mainframev commented
let's merge it later, when other breaking changes will be ready :)

2022-10-24 14:38 UTC, DSil commented
This will require an update on the orbit-themer package after #3615 is merged

2022-11-24 21:11 UTC, merged