Upgrade node, react, and gatsby
kiwicom/orbit pull request #3705
Opened 2022-12-29 12:34 UTC by DSil

# This Pull Request meets the following criteria:

- [x] Update node
- [x] Update React
- [x] Update testing-library and consequent tests and dependencies
- [ ] Update gatsby

2023-05-30 10:25 UTC, mainframev requested changes

2023-05-30 10:25 UTC, mainframev commented on docs/package.json
> +    "@types/adeira__js": "^2.1.0",
I think that it's redundant dependency, we dropped adeira :)

2023-05-30 19:46 UTC, mainframev requested changes

2023-05-31 08:47 UTC, DSil commented on packages/orbit-components/src/Select/__tests__/Select.test.tsx
> +    // This act can be removed after ORBIT-2464 is done
Well 2464 is done, so this can actually be removed 😄 nice spotted

2023-05-31 09:20 UTC, DSil commented on package.json
> +    "node": ">=18.0.0"
I did not notice any problem but good question. I noticed we don't have it for orbit-components, but we probably should 🤔 I will add, let me know if you're not in favor of it

2023-05-31 09:35 UTC, mainframev commented on packages/orbit-components/src/Select/__tests__/Select.test.tsx
> +    // This act can be removed after ORBIT-2464 is done
Yeah, I had to check the ticket :D

2023-05-31 09:47 UTC, mainframev commented
LGTM. Just remove the `babel-eslint`, seems like missed and it can be merged after 👍🏻

2023-05-31 09:48 UTC, mainframev approved these changes

2023-06-12 09:37 UTC, mainframev commented
found just one more small thing, could you please update @types/react and @types/react-dom to v18? and peerDependencies also to v18 🙏🏻

2023-06-23 09:28 UTC, mainframev commented
@DSil could you resolve conflicts, so we can merge that after the next minor release?

2023-08-22 05:56 UTC, merged