chore(Drawer): migrate to tailwind
kiwicom/orbit pull request #3956
Opened 2023-08-11 13:56 UTC by mainframev

Migration of Drawer to Tailwind

Had to add some additional setup to make it work: 

- added by default dir="ltr" attribute to storybook
- added tailwindcss3d plugin to our preset to support usage of Z axes, scale and etc.

[FEPL-1661](https://kiwicom.atlassian.net/browse/FEPLT-1661)

2023-08-11 13:57 UTC, mainframev commented on packages/orbit-components/src/Drawer/index.tsx
> +            : "translate-z-full lm:translate-z-[var(--lm-drawer-width)] translate-x-0 translate-y-0",
the animation of opening yet is not so smooth as current Drawer in master, I am working on make it work the same as there

2023-08-12 21:40 UTC, mainframev commented on packages/orbit-components/src/Drawer/__tests__/index.test.tsx
> +    expect(screen.getByTestId("test")).toHaveAttribute("aria-hidden", "true");
change to attribute matcher, as testing-library matches `toBeVisible` was not working properly as perhaps [criteria were not matched](https://github.com/testing-library/jest-dom#tobevisible) :shrug: But asserting it with attributes is also ok imo.

2023-08-12 21:41 UTC, mainframev commented on packages/orbit-components/src/Drawer/index.tsx
> -  const [overlayShown, setOverlayShown, setOverlayShownWithTimeout] = useStateWithTimeout<boolean>(
removed, as the difference is barely visible

2023-08-14 16:05 UTC, DSil requested changes
Just initial review, as some logic is missing or needs rethought 💪

2023-08-14 16:05 UTC, DSil commented on packages/orbit-components/src/Drawer/index.tsx
> +            !!onClose && noPadding && "mt-lg",
This used to be `!hasClose && noPadding`, but `hasClose = !!onClose`, so in here it should only be `!onClose && noPadding`, no?

2023-08-15 10:12 UTC, mainframev commented on packages/orbit-design-tokens/src/dictionary/definitions/component/drawer/drawer-background.json
> +          "value": "rgba(37, 42, 49, 0.5)"
yep, it will be better, I just defined that because it was not in the master yet

2023-08-15 10:13 UTC, mainframev commented on packages/orbit-components/src/Drawer/index.tsx
> -import getTransitionAnimation from "./helpers/getTransitionAnimation";
yes

2023-08-15 12:19 UTC, mainframev commented on packages/orbit-components/src/Drawer/index.tsx
> +            : "ltr:lm:translate-x-[var(--lm-drawer-width)] rtl:lm:-translate-x-[var(--lm-drawer-width)]",
this logic becomes redundant with tailwind (attaching the screenshots for comparison): 

local: 
![Screenshot 2023-08-15 at 14 18 00](https://github.com/kiwicom/orbit/assets/14054752/484db0f7-c82b-4878-9b10-98d7936b085a)
![Screenshot 2023-08-15 at 14 18 36](https://github.com/kiwicom/orbit/assets/14054752/7c519655-432a-4842-86ce-ca3c7279fb39)

remote master:
![Screenshot 2023-08-15 at 14 18 50](https://github.com/kiwicom/orbit/assets/14054752/16731625-ebd2-46f0-ad15-422424c67cad)
![Screenshot 2023-08-15 at 14 19 13](https://github.com/kiwicom/orbit/assets/14054752/2d8c9cda-94f0-4816-a7e9-ca293f845c0a)

2023-08-16 11:11 UTC, DSil commented on packages/orbit-design-tokens/src/dictionary/definitions/component/drawer/drawer-background.json
> +          "value": "rgba(37, 42, 49, 0.5)"
It was merged already, so you can rebase and make use of it 🤞

2023-08-16 11:13 UTC, DSil commented on packages/orbit-components/src/Drawer/index.tsx
> +            : "ltr:lm:translate-x-[var(--lm-drawer-width)] rtl:lm:-translate-x-[var(--lm-drawer-width)]",
It is not redundant. The translation has a specific logic attached to RTL **and** positioning of the drawer passed by the prop. And that logic is missing here.

Master:
![Aug-16-2023 13-11-12](https://github.com/kiwicom/orbit/assets/6265045/92415398-3d0e-424e-9173-6949ed348739)

Here:
![Aug-16-2023 13-09-39](https://github.com/kiwicom/orbit/assets/6265045/67ca41af-6b03-455a-9b31-c974f24c407e)

2023-08-16 11:49 UTC, mainframev commented on packages/orbit-components/src/Drawer/index.tsx
> +            : "ltr:lm:translate-x-[var(--lm-drawer-width)] rtl:lm:-translate-x-[var(--lm-drawer-width)]",
Now should be ok :)

2023-08-28 10:36 UTC, DSil requested changes
The first two commits do not belong here. Please remove them 🙏

2023-08-28 10:36 UTC, DSil commented on packages/orbit-design-tokens/output/docs-tokens.json
> +  "drawerOverlayBackground": {
This is incorrect. Probably a rebase problem. Building the tokens again should fix it

2023-08-28 14:46 UTC, mainframev commented
> LGTM. Just don't forget to fixup commits.
> 
> Also, I've been marking all tailwind migrations as a feat. Even though some don't add any change to the API, I think we would benefit from having it documented on the changelog. WDYT?

sure, makes sense, will reword 👍🏻

2023-08-28 15:51 UTC, DSil approved these changes
LGTM. The only failing test on the pipeline is the one that is not related to this PR. So we can either wait on that fix on the base branch (to avoid more commits on that branch until the problem is fixed) or we can merge this into the other one, preferably before the test fixing commits

2023-08-28 15:52 UTC, merged