ButtonGroup to Tailwind
kiwicom/orbit pull request #4046
Opened 2023-09-21 10:58 UTC by oreqizer

[WEBC-1754](https://kiwicom.atlassian.net/browse/FEPLT-1754)

2023-09-21 12:53 UTC, DSil requested changes
I notice something off here. I don't think it's related to this PR tho, but to the Button migration. (It happens in LTR and RTL).

Before:
<img width="172" alt="image" src="https://github.com/kiwicom/orbit/assets/6265045/eaea582f-934c-4b53-b500-cd7cb16c7e15">

Now:
<img width="172" alt="image" src="https://github.com/kiwicom/orbit/assets/6265045/e3a70895-7f7a-49fb-ac38-a408585c52ab">

Also, the `orbit-button-primitive-content` element is missing a style of `line-height: 1`, that used to have.

2023-09-21 12:53 UTC, DSil commented on packages/orbit-components/src/tmp-tailwind/ButtonGroup/types.d.ts
Not needed here

2023-09-21 12:53 UTC, DSil commented on packages/orbit-components/src/tmp-tailwind/ButtonGroup/index.tsx
> +    className="tb:first:[&>.orbit-button-primitive]:rounded-s-normal tb:last:[&>.orbit-button-primitive]:rounded-e-normal flex space-x-[1px] rtl:space-x-reverse [&>.orbit-button-primitive]:rounded-no
`space-x-[1px]` can be `space-x-px`, I believe

2023-09-22 17:12 UTC, mainframev approved these changes

2023-09-22 17:26 UTC, merged