chore(tokens): add tokensToCssVars utility function
kiwicom/orbit pull request #4088
Opened 2023-10-15 14:08 UTC by mainframev

[Doc](https://docs.google.com/document/d/13q8UrRqCzvnQ9Pv6wH5QS_7SG4eeC7hdXTtvqNhWc9k/edit?usp=sharing) 

Idk, adding it for now and opening it for discussion. In my opinion, this function shouldn't be a part of the tokens package to help fix WL, better will be to define this function directly in the core repository and in simpler variations (to rewrite only the flat object tokens for specific WL). 

In case to keep it here, this function should serve to create tokens with css variables. So something similar to our current [`createTokens`](https://github.com/kiwicom/orbit/blob/master/packages/orbit-design-tokens/src/js/createTokens.ts)

2023-10-17 10:49 UTC, DSil requested changes

2023-10-17 10:49 UTC, DSil commented on packages/orbit-components/src/OrbitProvider/index.tsx
> +    style.innerText = tokensToCssVars({ tokens: theme.orbit }).replace(/\s/g, "");
This doesn't work. It needs a selector.

```suggestion
    style.innerText = `
    :root {
      ${tokensToCssVars({ tokens: theme.orbit }).replace(/\s/g, "")}
    }
    `;
```

2023-10-17 16:11 UTC, DSil reviewed
LGTM, just one question.

Also, this should be a fix commit, no? This is a broken feature we currently have.

2023-10-17 16:11 UTC, DSil commented on packages/orbit-components/src/OrbitProvider/index.tsx
> +      "",
I would prefer this replace to be inside the function, and not here, if possible.

2023-10-17 17:27 UTC, mainframev commented
> LGTM, just one question.
> 
> Also, this should be a fixed commit, no? This is a broken feature we currently have.

Do you mean the OrbitProvider adjustment? no, it's a chore, for the user API is not changed 🤔 Under the hood are css variables, but they won't need any additional setup.

2023-10-18 07:55 UTC, DSil commented
Orbit was broken for WL. This change fixes that problem. Therefore, it's a fix. A fix commit does not require an API change.

2023-10-18 10:40 UTC, DSil approved these changes

2023-10-19 08:16 UTC, merged