feat(CarrierLogo): migrate to Tailwind
kiwicom/orbit pull request #4098
Opened 2023-10-18 14:34 UTC by mvidalgarcia

Closes FEPLT-1763

 Storybook: https://orbit-mainframev-tw-carrier-logo.surge.sh

2023-10-19 16:29 UTC, mainframev commented
idk why, but visual tests are different in master comparing to this branch 
![Screenshot 2023-10-19 at 18 28 52](https://github.com/kiwicom/orbit/assets/14054752/ceb243cc-8814-46ae-a70b-429de5792fad)
![Screenshot 2023-10-19 at 18 28 57](https://github.com/kiwicom/orbit/assets/14054752/bc53c063-45d7-48f0-aec4-33253c073823)

2023-10-19 16:48 UTC, mainframev requested changes

2023-10-20 10:26 UTC, mvidalgarcia commented
> idk why, but visual tests are different in master comparing to this branch

I think master is broken, the `max-width: 100%` in the `img` element on the tailwind preflight is messing up with inline logos.

![image](https://github.com/kiwicom/orbit/assets/8863238/95d4ca20-7bde-4ea6-811b-1c2c7d1e567c)

If you set it to `max-width: none`, as it's done in the Tailwind commit, many hidden logos show up.

Do you think we should fix this first on master to get the right screenshots?

2023-10-20 10:32 UTC, mvidalgarcia commented on packages/orbit-components/src/CarrierLogo/index.tsx
> +            inlineStacked && "[&_+_&]:-ms-xs", // equivalent to &:not(:first-child)
TIL! 
Yes yes, that helps a lot! Thanks!

2023-10-20 13:33 UTC, mainframev commented
> > idk why, but visual tests are different in master comparing to this branch
> 
> I think master is broken, the `max-width: 100%` in the `img` element on the tailwind preflight is messing up with inline logos.
> 
> ![image](https://user-images.githubusercontent.com/8863238/276901752-95d4ca20-7bde-4ea6-811b-1c2c7d1e567c.png)
> 
> If you set it to `max-width: none`, as it's done in the Tailwind commit, many hidden logos show up.
> 
> Do you think we should fix this first on master to get the right screenshots?

This PR already is fixing that, I think we can just wait for merge of this and that will automatically fix the snapshot after

2023-10-23 09:54 UTC, mainframev commented
> idk why, but visual tests are different in master comparing to this branch
> 
> ![Screenshot 2023-10-19 at 18 28 52](https://user-images.githubusercontent.com/14054752/276685787-ceb243cc-8814-46ae-a70b-429de5792fad.png) ![Screenshot 2023-10-19 at 18 28 57](https://user-images.githubusercontent.com/14054752/276685796-bc53c063-45d7-48f0-aec4-33253c073823.png)

@mvidalgarcia I also think that the visual test is missing 3 or 4 carrier logos with inlinestacked and rounded properties, can it be added? 🙏🏻

2023-10-23 10:07 UTC, mvidalgarcia commented
@mainframev it was broken on [prod](https://kiwicom.github.io/orbit/?path=/story/carrierlogo--visual-test). It should be fixed [now](https://orbit-mainframev-tw-carrier-logo.surge.sh/?path=/story/carrierlogo--visual-test).

I've already performed the [visual tests](https://www.chromatic.com/build?appId=6523bafdbc6087c220b3cc48&number=135), comparing master with [master fixed](https://github.com/kiwicom/orbit/commit/5c9d19edcf93d19a8294edd0d582e55294f99cd4).

2023-10-23 10:09 UTC, mainframev commented
> @mainframev it was broken on [prod](https://kiwicom.github.io/orbit/?path=/story/carrierlogo--visual-test). It should be fixed [now](https://orbit-mainframev-tw-carrier-logo.surge.sh/?path=/story/carrierlogo--visual-test).
> 
> I've already performed the [visual tests](https://www.chromatic.com/build?appId=6523bafdbc6087c220b3cc48&number=135), comparing master with [master fixed](https://github.com/kiwicom/orbit/commit/5c9d19edcf93d19a8294edd0d582e55294f99cd4).

@mvidalgarcia I know it was broken, I mentioned it above. I meant, that there are 3 and 4, but they aren't rounded, could you also add rounded variations?

2023-10-23 10:16 UTC, mvidalgarcia commented
@mainframev Ah sorry, I hadn't understood you. 

I've added `inlineStacked rounded` variations.

2023-10-23 12:23 UTC, merged